latestnode.settings:
  type: config_object
  label: 'Config object for latestnode'
  mapping:
    node_type:
      type: string
      label: 'Nodes Type'
    node_count:
      type: integer
      label: 'Nodes Count'
