<?php

/**
 * @file
 * This file demonstrates how to use hook functions
 */

/**
 * Implements hook_cron()
 */
function mymodule_cron() {
  \Drupal::messenger()->addMessage(t('Hello from mymodule cron hook! :)'));
}

/**
 * Implements hook_form_alter
 */
function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_article_edit_form') {
    $form['actions']['submit']['#value'] = t('Save this awesome article!');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function mymodule_preprocess_region(&$variables) {
  if ($variables['region'] == 'footer') {
    $currentUserRoles = \Drupal::currentUser()->getRoles();
    $variables['elements']['userroles']['content'] = [
      '#theme' => 'mytemplate',
      '#roles' => $currentUserRoles,
      '#cache' => [
        'max-age' => 300,
        'contexts' => ['user.roles'],
      ],
    ];
    foreach ($currentUserRoles as $role) {
      $variables['elements']['userroles']['content']['#attributes']['class'][] = $role;
    }
  }
  /*$variables['page']['footer']['#theme'] = 'mytemplate'; //[myblock]=[#theme => ]
  $currentUserRoles = \Drupal::currentUser()->getRoles();
  $variables['page']['footer']['#roles'] = $currentUserRoles;
  $variables['#cache'] = [
    'max-age' => 300,
    'tags' => ['user.roles'],
  ];
  $roles = '';
  foreach ($currentUserRoles as $role) {
    $roles .= $role . ' ';
  }
  /*$variables['page']['footer']['#prefix'] = '<div class="' . $roles . '">';
  $variables['page']['footer']['#suffix'] = '</div>';*/
  //$variables['page']['footer']['#attributes']['class'][] = $currentUserRoles;*/
}

/**
 * Implements hook_theme().
 */
function mymodule_theme($existing, $type, $theme, $path) {
  return [
    'mytemplate' => [
      'variables' => ['roles' => NULL],
    ],
    'mymodule.latestnodes' => [
      'variables' => ['latestnodes' => NULL],
    ],
  ];
}
