<?php

/**
 * @file
 * This file contains hook functions for mymodule module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_cron().
 */
function mymodule_cron() {
  \Drupal::messenger()->addMessage(t('Hello from mymodule cron hook! :)'));
}

/**
 * Implements hook_form_alter().
 */
function mymodule_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_article_edit_form') {
    $form['actions']['submit']['#value'] = t('Save this awesome article!');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function mymodule_preprocess_region(&$variables) {
  if ($variables['region'] == 'footer') {
    $currentUserRoles = \Drupal::currentUser()->getRoles();
    $variables['userroles'] = [
      '#theme' => 'mytemplate',
      '#roles' => $currentUserRoles,
      '#cache' => [
        'max-age' => 300,
        'contexts' => ['user.roles'],
      ],
      '#prefix' => '<div class="' . implode(' ', $currentUserRoles) . '">',
      '#suffix' => '</div>',
    ];
  }
}

/**
 * Implements hook_theme().
 */
function mymodule_theme($existing, $type, $theme, $path) {
  return [
    'mytemplate' => [
      'variables' => ['roles' => NULL],
    ],
    'mymodule.latestnodes' => [
      'variables' => ['latestnodes' => NULL],
    ],
  ];
}
